// CLASSES AND OBJECTS

// SYNTAX
// HERE WE WILL DESCRIBE ITS SYNTAX WITH HELP OF AN EXAMPLE OF TEACHER

// CREATING A CLASS
    // class Teacher{
    // PROPERTIES OR ATTRIBUTES
    // string name;
    // string dept;
    // string subject;
    // double salary;

    // Methods or Member functions
    // void changedept(string newdept){
    //     dept = newdept;
    // }
    // };

// CREATING OBJECT
    // Teacher t1;  Here Teacher t1 object is created.
    // Teacher t2;
